/**
 * Realistic mock pipeline response matching ARCHITECTURE.md.
 * Flip USE_MOCK to true only for offline UI demos.
 */
/** Set true only for offline UI demos when Flask is down. Keep false for real API. */
export const USE_MOCK = false;

export const MOCK_HEALTH = {
  status: "ok",
  demand_model: true,
  price_model: true,
  groq_enabled: true,
  groq_model: "llama-3.3-70b-versatile",
  databricks_enabled: false,
};

export const MOCK_RESULT = {
  generated_at: "2026-07-25T14:30:00",
  horizon_month: "2026-08",
  inputs: { available_containers: 6, container_type: "20FT", top_n: 3 },
  stage1_demand: {
    note: "Top opportunities ranked by demand model score.",
    top_opportunities: [
      { rank: 1, commodity: "Onion", country: "Bangladesh", demand_score: 0.91, mentions: 7 },
      { rank: 2, commodity: "Rice", country: "UAE", demand_score: 0.78, mentions: 5 },
      { rank: 3, commodity: "Wheat", country: "Indonesia", demand_score: 0.64, mentions: 3 },
    ],
  },
  stage2_prices: {
    predictions: [
      {
        commodity: "Onion",
        current_price_inr: 1850,
        predicted_next_month_price_inr: 2120,
        predicted_change_pct: 14.6,
      },
      {
        commodity: "Rice",
        current_price_inr: 3200,
        predicted_next_month_price_inr: 3350,
        predicted_change_pct: 4.7,
      },
      {
        commodity: "Wheat",
        current_price_inr: 2450,
        predicted_next_month_price_inr: 2380,
        predicted_change_pct: -2.9,
      },
    ],
  },
  stage3_logistics: [
    {
      commodity: "Onion",
      country: "Bangladesh",
      demand_score: 0.91,
      predicted_india_price_inr: 2120,
      india_port: "Kolkata",
      destination_port: "Chittagong",
      origin: "Nashik",
      cost_per_ton_usd: 42.5,
      cost_per_container_usd: 850,
      total_transit_days: 6,
      service_type: "direct",
      decision_summary: "Short coastal haul from Kolkata keeps logistics lean.",
      net_profit_usd_per_ton: 68.4,
      profit: {
        net_profit_usd_per_ton: 68.4,
        net_profit_usd_per_container: 1368,
        net_profit_usd_for_allocation: 0,
      },
      ok: true,
      error: null,
    },
    {
      commodity: "Rice",
      country: "UAE",
      demand_score: 0.78,
      predicted_india_price_inr: 3350,
      india_port: "Mundra",
      destination_port: "Jebel Ali",
      origin: "Punjab",
      cost_per_ton_usd: 78.2,
      cost_per_container_usd: 1564,
      total_transit_days: 11,
      service_type: "direct",
      decision_summary: "Mundra → Jebel Ali is the lowest-cost Gulf corridor.",
      net_profit_usd_per_ton: 52.1,
      profit: {
        net_profit_usd_per_ton: 52.1,
        net_profit_usd_per_container: 1042,
        net_profit_usd_for_allocation: 0,
      },
      ok: true,
      error: null,
    },
    {
      commodity: "Wheat",
      country: "Indonesia",
      demand_score: 0.64,
      predicted_india_price_inr: 2380,
      india_port: "Chennai",
      destination_port: "Jakarta",
      origin: "Madhya Pradesh",
      cost_per_ton_usd: 95.0,
      cost_per_container_usd: 1900,
      total_transit_days: 14,
      service_type: "transshipment",
      decision_summary: "Longer SE Asia leg; allocate only if containers remain.",
      net_profit_usd_per_ton: 31.8,
      profit: {
        net_profit_usd_per_ton: 31.8,
        net_profit_usd_per_container: 636,
        net_profit_usd_for_allocation: 0,
      },
      ok: true,
      error: null,
    },
  ],
  stage4_container_priority: {
    summary: "Ship Onion → Bangladesh first with 3 of 6 containers.",
    export_first: {
      commodity: "Onion",
      country: "Bangladesh",
      containers: 3,
      india_port: "Kolkata",
      destination_port: "Chittagong",
      net_profit_usd_per_ton: 68.4,
    },
    allocations: [
      {
        priority_rank: 1,
        commodity: "Onion",
        country: "Bangladesh",
        containers_allocated: 3,
        priority_score: 0.92,
        india_port: "Kolkata",
        destination_port: "Chittagong",
        net_profit_usd_per_ton: 68.4,
        export_first: true,
      },
      {
        priority_rank: 2,
        commodity: "Rice",
        country: "UAE",
        containers_allocated: 2,
        priority_score: 0.74,
        india_port: "Mundra",
        destination_port: "Jebel Ali",
        net_profit_usd_per_ton: 52.1,
        export_first: false,
      },
      {
        priority_rank: 3,
        commodity: "Wheat",
        country: "Indonesia",
        containers_allocated: 1,
        priority_score: 0.51,
        india_port: "Chennai",
        destination_port: "Jakarta",
        net_profit_usd_per_ton: 31.8,
        export_first: false,
      },
    ],
  },
  final_decisions: {
    summary:
      "Prioritise Onion to Bangladesh (3×20FT). Fill remaining slots with Rice to UAE, then Wheat to Indonesia.",
    export_first: {
      commodity: "Onion",
      country: "Bangladesh",
      containers: 3,
    },
    lanes: [
      {
        commodity: "Onion",
        country: "Bangladesh",
        india_port: "Kolkata",
        destination_port: "Chittagong",
        predicted_india_price_inr: 2120,
        cost_per_ton_usd: 42.5,
        net_profit_usd_per_ton: 68.4,
        net_profit_usd_for_allocation: 4104,
        containers_allocated: 3,
        priority_rank: 1,
        export_first: true,
        decision_summary: "Highest demand + strongest net profit per ton.",
        ok: true,
      },
      {
        commodity: "Rice",
        country: "UAE",
        india_port: "Mundra",
        destination_port: "Jebel Ali",
        predicted_india_price_inr: 3350,
        cost_per_ton_usd: 78.2,
        net_profit_usd_per_ton: 52.1,
        net_profit_usd_for_allocation: 2084,
        containers_allocated: 2,
        priority_rank: 2,
        export_first: false,
        decision_summary: "Solid Gulf demand with moderate logistics cost.",
        ok: true,
      },
      {
        commodity: "Wheat",
        country: "Indonesia",
        india_port: "Chennai",
        destination_port: "Jakarta",
        predicted_india_price_inr: 2380,
        cost_per_ton_usd: 95.0,
        net_profit_usd_per_ton: 31.8,
        net_profit_usd_for_allocation: 636,
        containers_allocated: 1,
        priority_rank: 3,
        export_first: false,
        decision_summary: "Fill leftover capacity only.",
        ok: true,
      },
    ],
    price_cards: [],
  },
  agent_explanations: {
    demand_agent:
      "Bangladesh onion demand leads on score 0.91 with seven supporting mentions. UAE rice and Indonesia wheat follow.",
    price_agent:
      "Onion prices are projected up ~15% next month. Rice edges higher; wheat softens slightly.",
    logistics_agent:
      "Kolkata→Chittagong is the leanest lane. Mundra→Jebel Ali is next. Chennai→Jakarta carries longer transit.",
    container_agent:
      "With only 6 containers, allocate 3 to Onion first, then 2 Rice, 1 Wheat — ranking by demand, buy price, logistics, and net profit.",
    supervisor_agent:
      "Board call: export Onion to Bangladesh first. Review net-profit cards, then ask the RAG desk for document/tariff checks.",
  },
  llm: {
    enabled: true,
    model: "llama-3.3-70b-versatile",
    source: "groq",
  },
};
